export class Auth {
  public static readonly token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhMGRlODQ5ZC1hODlkLTRlODItODY3MS05MGFkM2Q2NGRiNjciLCJwbGF0Zm9ybSI6InN1YnNjcmlwdGlvbnMiLCJpYXQiOjE2Nzg4ODgyODYsImV4cCI6MTY3OTc4ODI4Nn0.0BfNAqPpJEofUantC9i-ZnaPtAr7AnbGb6xCNkpAHgY";
}
